### ISSUE TITLE
xbuild issue

### ISSUE THREAD

**Issue by Artysteel** [alexbakker/SharpTox#25]
Good day,

Im getting 31 Errors after executing 
xbuild /p:Configuration="Debug POSIX"

Whole process that I did:
Install TOXCORE
sudo apt-get install build-essential libtool autotools-dev automake checkinstall check git yasm libsodium13 libsodium-dev
sudo apt-get install libopus-dev libvpx-dev pkg-config
git clone https://github.com/irungentoo/toxcore.git toxcore
cd toxcore
autoreconf -i
./configure
make
sudo make install

Sharp TOX
sudo apt-get install mono-complete
sudo apt install nuget
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update
sudo apt-get install ca-certificates-mono
sudo nuget restore
xbuild /p:Configuration="Debug POSIX"
FAILED HERE

**Comment by Impyy** [comment]
Can you also share the output of xbuild?

**Comment by Artysteel** [comment]
XBuild Engine Version 14.0
Mono, Version 4.8.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 26/03/2017 12:26:00.
__________________________________________________
Project "/home/pi/sharptox/SharpTox.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug POSIX|Any CPU".
        Target Build:
                Project "/home/pi/sharptox/SharpTox/SharpTox.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug POSIX Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target _GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:"obj/Debug POSIX/SharpTox.dll" Av/ToxAvAudioFrame.cs Av/ToxAvEventArgs.cs Av/ToxAvHandle.cs Av/ToxAvVersion.cs Av/ToxAvVideoFrame.cs Core/Tox.cs Core/ToxData.cs Core/ToxDataInfo.cs Core/ToxEventArgs.cs Core/ToxHandle.cs Core/ToxId.cs Core/ToxKey.cs Core/ToxOptions.cs Core/ToxVersion.cs Dns/ToxDnsHandle.cs Encryption/ToxEncryption.cs Encryption/ToxEncryptionErrors.cs Encryption/ToxEncryptionFunctions.cs Encryption/ToxEncryptionKey.cs Encryption/ToxPassKey.cs Properties/AssemblyInfo.cs Av/ToxAv.cs Av/ToxAvDelegates.cs Av/ToxAvEnums.cs Av/ToxAvFunctions.cs Core/ToxConstants.cs Core/ToxDelegates.cs Dns/ToxDns.cs Dns/ToxDnsFunctions.cs Core/ToxEnums.cs Core/ToxFunctions.cs Core/ToxNode.cs Core/ToxTools.cs Core/ToxFileInfo.cs "obj/Debug POSIX/.NETFramework,Version=v4.5.AssemblyAttribute.cs" /target:library /define:"DEBUG;TRACE;POSIX" /doc:bin/Debug/SharpTox.XML /nostdlib /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/home/pi/sharptox/SharpTox/SharpTox.csproj".-- FAILED
                Done building project "/home/pi/sharptox/SharpTox/SharpTox.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/home/pi/sharptox/SharpTox.sln".-- FAILED
Done building project "/home/pi/sharptox/SharpTox.sln".-- FAILED

Build FAILED.
Errors:

/home/pi/sharptox/SharpTox.sln (default targets) ->
(Build target) ->
/home/pi/sharptox/SharpTox/SharpTox.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS0518: The predefined type `System.Object' is not defined or imported
        CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
        CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
        CSC: error CS0518: The predefined type `System.Single' is not defined or imported
        CSC: error CS0518: The predefined type `System.Double' is not defined or imported
        CSC: error CS0518: The predefined type `System.Char' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
        CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
        CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
        CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
        CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
        CSC: error CS0518: The predefined type `System.String' is not defined or imported
        CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
        CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.Void' is not defined or imported
        CSC: error CS0518: The predefined type `System.Array' is not defined or imported
        CSC: error CS0518: The predefined type `System.Type' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

         0 Warning(s)
         31 Error(s)

Time Elapsed 00:00:04.9370570

**Comment by Impyy** [comment]
What happens if you add ``/p:TargetFrameworkVersion="v4.5"`` to the xbuild call?

**Comment by Artysteel** [comment]
Outputs same. Could it be I am missing .NET framework?

**Comment by Impyy** [comment]
Strange, I don't know what the issue is, sorry. You'll have to ask the mono people.

**Comment by Artysteel** [comment]
No worries, thanks for looking into this. Will try to fix it myself anyway =) Currently using pure C lang, but C# is more friendly
