### ISSUE TITLE
Building a client

### ISSUE THREAD

**Issue by LloydCorfex** [alexbakker/SharpTox#29]
After some trouble i finally have an error free copy of this repo.

But what now? 
Where to start?
Which funtions are available?

Do you have any documentation (on how to build an own Tox messenger in C#)?

**Comment by alexbakker** [comment]
SharpTox itself doesn't have much documentation. Most of the functions map directly to the ones in toxcore: https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h
